// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard__5 = "CgkI9830ha0JEAIQBA"; // <GPGSID>
        public const string leaderboard__6 = "CgkI9830ha0JEAIQBw"; // <GPGSID>
        public const string achievement_thank_you_for_loving_our_application = "CgkI9830ha0JEAIQEw"; // <GPGSID>
        public const string achievement_are_you_sure_youre_a_person = "CgkI9830ha0JEAIQEA"; // <GPGSID>
        public const string achievement_fast_fast_fast = "CgkI9830ha0JEAIQDw"; // <GPGSID>
        public const string leaderboard__8 = "CgkI9830ha0JEAIQCQ"; // <GPGSID>
        public const string leaderboard__7 = "CgkI9830ha0JEAIQCA"; // <GPGSID>
        public const string leaderboard__9 = "CgkI9830ha0JEAIQCg"; // <GPGSID>
        public const string leaderboard__10 = "CgkI9830ha0JEAIQCw"; // <GPGSID>
        public const string leaderboard_infinite_mod = "CgkI9830ha0JEAIQDg"; // <GPGSID>
        public const string achievement_wheres_the_end = "CgkI9830ha0JEAIQEQ"; // <GPGSID>
        public const string achievement_are_you_machine = "CgkI9830ha0JEAIQEg"; // <GPGSID>

}

